name: arun
favicon: null
layout_spectrum: 0.00178
typography_spectrum: 0.03580678254365921
title: A Run For Your
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5118223722092807
  lightness: 0.19233591784723103
  saturation: 0.5323736630380154
  rhythmicContrast: 0.22989077330566943
purpose: []
